apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: kafka
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
   app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: tmaxcloudck/postgres-cron:b5.0.0.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: TZ
            value: 'Asia/Seoul'
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
            requests:
              cpu: "300m"
              memory: "100Mi"

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: kafka
type: Opaque
data:
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==

